Remove deprecated group functions from universal API
inrupt/solid-client-js pull request #1447
Opened 2022-02-01 17:39 UTC by matthieubosquet

The `getAccessFor`, `getAccessForAll` and `setAccessFor` functions are aliases for managing group-based access.

This should be removed as part of the deprecation of groups in ACP.

2022-02-02 08:29 UTC, NSeydoux commented
Would this be a breaking change for the current "main" ACP entrypoint, or does it only affect `acp_v4` ?

2022-02-02 12:40 UTC, matthieubosquet commented
@NSeydoux the `getAccessFor`, `getAccessForAll` and `setAccessFor` functions are available through the universal API.

```typescript
import { getAccessFor, getAccessForAll, setAccessFor } from "@inrupt/solid-client/src/access/universal";
// OR
import { access } from "@inrupt/solid-client";
```

So, once the 1.2 update gets through, the group based permissions aren't a thing anymore. You'd still be able to import them through universal_v1 directly.

2022-02-02 14:04 UTC, matthieubosquet commented
@NSeydoux I actually added the deprecation markers in the related module. I think it was just an oversight.

But really this should be removed altogether from the default universal API.

See that commit for deprecation: https://github.com/inrupt/solid-client-js/pull/1447/commits/0535cbcaf8154f4bea41c836c3c6053604a6f58c

2022-02-02 15:13 UTC, ThisIsMissEm approved these changes
I think this is good; If I'm understanding correctly universal_v2 isn't really being used by anyone at present, and those methods shouldn't have been part of it's API in the first place as they were deprecated beforehand

2022-02-02 15:17 UTC, ajacksified requested changes
As discussed in slack - because it _is_ public we should not break the interface, regardless of whether it was previously deprecated, without a major version change. Major version bumps are required for the removal of deprecated functions.

2022-02-02 15:42 UTC, ThisIsMissEm commented
@ajacksified I don't think this does break the public interface, as you currently have to explicitly import from `"@inrupt/solid-client/src/access/universal_v2";` or use `access_v2`, both of which aren't currently documented: https://docs.inrupt.com/developer-tools/api/javascript/solid-client/modules/access_universal.html

Though, switching `access/universal` from `access/universal_v1` to `access/universal_v2` WOULD be a breaking change.

2022-02-02 15:43 UTC, ThisIsMissEm commented
Or would we actually need an `access/universal_v3` now, which omits those functions?

2022-02-02 15:55 UTC, ajacksified commented
They're not documented but they are exported by both our index file and by direct import. The fact that they're exported was probably a mistake at the time, but because they are, regardless of the status of documentation, they are part of the public interface and should not change.

access/universal_v3 makes sense - that's the conclusion @matthieubosquet and I came to in Slack.

2022-02-08 14:28 UTC, ajacksified approved these changes

2022-02-08 14:30 UTC, merged