Fix/documentation clarification
inrupt/solid-client-js pull request #1631
Opened 2022-06-02 13:09 UTC by solid-akb

Small updates to documentation:

There were a few spots where the argument is called "dataset" but really it's the "datasetIri". The Type is correct, just updating the name for documentation purposes.

2022-06-02 13:59 UTC, ajacksified submitted a review, later dismissed
The consistency of the improved parameter names is nice!

2022-06-02 14:26 UTC, solid-akb commented on src/resource/file.ts
> +  fileUrl: Url | UrlString,
Done

2022-06-02 14:54 UTC, ThisIsMissEm requested changes
The changes aren't quite correct, as all these methods can accept a URL or a SolidDataset (with resource info), what I'd recommend doing is just updating the typedocs so the parameter name matches the argument name, but leave the implementation as-is.

2022-07-19 22:24 UTC, ThisIsMissEm approved these changes

2022-07-19 22:56 UTC, ThisIsMissEm commented
@solid-akb I've rebased this, and flattened it into a single commit, whilst keeping you as the author (I used your GitHub noreply as the author address)

2022-07-20 00:14 UTC, merged