Updated how we create object
inrupt/solid-client-js pull request #1846
Opened 2023-01-25 16:35 UTC by solid-akb

This PR updates how we create the initial object that tracks the dataset changelog. 

This is important because it protects against [prototype pollution](https://learn.snyk.io/lessons/prototype-pollution/javascript/).

2023-01-25 19:13 UTC, ThisIsMissEm requested changes
On the following lines there's a bunch of `??= {}` which also need to be changed too to `Object.create(null)`

2023-01-26 18:01 UTC, solid-akb commented
@ThisIsMissEm Thanks for the comment above. This begs the question, is there a way to check that the problem is fixed in SonarCloud before the PR is created or at least before merge? This PR passed all SonarCloud Github actions, but perhaps it probably shouldn't have.

2023-01-26 18:19 UTC, ThisIsMissEm commented
> @ThisIsMissEm Thanks for the comment above. This begs the question, is there a way to check that the problem is fixed in SonarCloud before the PR is created or at least before merge? This PR passed all SonarCloud Github actions, but perhaps it probably shouldn't have.

Honestly, I'm not sure! I would've expected SonarCloud to still be failing here, as the vulnerability wasn't entirely fixed?

2023-01-28 00:00 UTC, solid-akb commented
@ThisIsMissEm I made the fixes requested above. 

Also did a little dive in SonarCloud world. We probably don't want to make SonarCloud involved at the PR level because then it will flag everything. For now we can make the changes and then see the updates in SonarCloud after the merge, but I am still on the lookout with my work with setting up SonarQube in AMI if we can find a happy medium (like turning off certain flags that we know we will experience and are ok to push through).

2023-01-31 00:39 UTC, ThisIsMissEm approved these changes

2023-01-31 18:49 UTC, merged