Integrate problem details into Solid client library
inrupt/solid-client-js pull request #2458
Opened 2024-08-14 18:31 UTC by acoburn

This integrates the `@inrupt/solid-client-errors` library into this codebase.

This keeps the `FetchError` class compatible with its current state but adds a new async function: `problemDetails()`, which allows a consumer of the library to access the underlying problem details data, if a server returns such data.

2024-08-16 13:56 UTC, acoburn commented on src/resource/resource.test.ts
> +
Resolved in https://github.com/inrupt/solid-client-js/pull/2458/commits/aa7cb4bec115cfe4190e22c8a6957b6e0f172098

2024-08-19 11:03 UTC, jholleran commented on src/resource/resource.ts
> +  async problemDetails(): Promise<ProblemDetails> {
This is different to the `problemDetails()` function in: https://github.com/inrupt/solid-client-errors-js/blob/main/src/http/httpError.ts#L83. This difference will mean clients will have to handle errors differently.

This should be `get problemDetails()` so a client can call it like this `error.problemDetails`. Also it should not be async.

2024-08-20 08:55 UTC, jholleran requested changes
There is one other change that the e2e tests are showing up around ACP tests that I'm working on and will add it here.

2024-08-20 09:57 UTC, jholleran approved these changes
@NSeydoux I've reverted that change I made as I now don't think its needed. I had another look and its currently not called anywhere internally where we would get an error response. In the two places it is called one is a HEAD request and the other does a status code check before calling the function.

2024-08-20 10:00 UTC, NSeydoux approved these changes

2024-08-20 10:18 UTC, merged