Added `internal_getClientAccess`
inrupt/solid-client-js pull request #884
Opened 2021-03-05 17:16 UTC by NSeydoux

This adds a function to read which access are granted to a given Client
App for a given resource.

Note that currently, this function isn't available as part of the public
API, because it is only implemented for resources which access control
is based on ACP.

The current suggestion is to not expose this feature as part of the universal API until client access control is clarified for WAC. In order to make this function part of a public API, an upcoming PR should change the current `src/access/acp.ts` into `src/access/acp.internal.ts`, move functions we want to add to the public API to `src/access/acp.ts`, and add the latter to the export map. 

# Checklist

- [X] All acceptance criteria are met.
- [X] Relevant documentation, if any, has been written/updated.
- [ ] The changelog has been updated, if applicable.
- [X] Commits in this PR are minimal and [have descriptive commit messages](https://chris.beams.io/posts/git-commit/).

2021-03-08 12:37 UTC, Vinnl requested changes
I think it's a bit early to add this to the high-level ACP API, both because it's not actually accessible here yet, but also because it's not clear how this would interact with Agent or Group access. (So for example, if I set both Agent and Group access, then someone needs to be either that Agent or in that Group for either to apply. However, if I set Client access, does that mean that anyone using that Client can change the data? Or should it be combined with an Agent or Group Rule, and if so how?)

And of course, the low-level API, i.e. the one that should make all functionality available, still doesn't support with these changes.

So I think the implementation we want to go for here is not in `access/acp`, but rather in `acp/rule`. What do you think? (I hope you haven't spent too much effort on this... Sorry :disappointed:  )

2021-03-09 08:34 UTC, NSeydoux commented
No worries, your comments are valid, and to be honest it wasn't that much work.

2021-03-09 09:02 UTC, Vinnl approved these changes
As discussed, let's rename references to "PublicClient" to "AnyClient". Other than that just a small polishing up of the test and we're good to go :)

2021-03-09 09:37 UTC, Vinnl commented on src/acp/rule.test.ts
> +    expect(hasAnyClient(rule)).toEqual(false);
Oh btw, booleans are atomic values too, so `.toBe` works for those :)

2021-03-09 16:45 UTC, merged